apiVersion: v1
kind: Service
metadata:
  name: ftx-notify-service
  namespace: ftx-notify
spec:
  selector:
    app: ftx-notify-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftx-notify-app
  namespace: ftx-notify
  labels:
    app: ftx-notify-app
spec:
  selector:
    matchLabels:
      app: ftx-notify-app
  template:
    metadata:
      labels:
        app: ftx-notify-app
    spec:
      containers:
      - name: ftx-notify-app
        image: wiwatsrt/ftx-notify-bot
        env:
        - name: NODE_ENV
          value: "production"
        envFrom:
        - secretRef:
            name: ftx-notify-secrets
        ports:
        - containerPort: 3000
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      serviceAccountName: default
