---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ftx-notify-secrets
  namespace: ftx-notify
  labels:
    app: ftx-notify-app
    component: secrets
stringData:
  TELEGRAM_BOT_TOKEN: "<TELEGRAM_BOT_TOKEN>"
  TELEGRAM_CHAT_ID: "<TELEGRAM_CHAT_ID>"
data:
  FTX_ACCOUNTS: |
    data_in_base64
